[package]
name = "main_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
axum = "0.5.15"
async-graphql = "4.0.12"
async-graphql-axum = "4.0.12"
tokio-postgres = "0.7.7"
chrono = "0.4.22"
rust-argon2 = "1.0.0"
uuid = {version = "1.1.2", features = ["v4", "fast-rng"]}
dotenv = "0.15.0"