[package]
name = "main_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
axum = "0.5.15"
async-graphql = "4.0.10"
async-graphql-axum = "4.0.10"
tokio-postgres = "0.7.7"
dotenv = "0.15.0"